---
output: github_document
bibliography:
- inst/refs.bib
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)

  library(magrittr)

```

The goal of `envSDM` is to help automate the preparation, tuning and prediction
of species distribution models. `envSDM` attempts to make decisions at each of
these steps that are robust(ish) for running SDMs for many, many taxa.

If you are looking for packages to run species distribution models
(or ecological niche models) there are plenty of better packages to choose from:

* [tidysdm](https://cran.r-project.org/web/packages/tidysdm/index.html). Future
versions of envSDM are likely to move towards this framework.
* [flexsdm](https://sjevelazco.github.io/flexsdm/)
* [ENMeval](https://cran.r-project.org/web/packages/ENMeval/index.html)

`envSDM` assumes that your are trying to run many, many taxa, thus there is no
option to run a single taxa in parallel. The functions are all designed around
the potential to run many taxa in parallel (assuming each taxa is run on a
single core). For the long running functions, there is the option to
return either: the object, or the path to an .rds file into which the object is
saved.

Preparation includes generating:

* generation of a (possibly buffered) minimum convex polygon around
presences to limit the rest of the process (predict boundary)
* density raster of presences
* spatially thickened [@RN4592] background points against density raster
* balanced spatial folds from the presences and background points
* environmental data for presences and background points
* ensuring the environmental variables used are not correlated beyond a
threshold, per taxa

Tuning includes:

* three possible algorithms:
    + `randomForest::randomForest()`
        + always using the `randomForest()` `sampsize` argument downsample to
        the minimum number of presences
    + `maxnet::maxnet()`
    + `predicts::envelope()`
* ability to use multiple metrics for choosing a 'best' tune

Prediction includes:

* only predicting to a predict boundary established during the preparation
* threshold to maximum of specificity + sensitivity

## Installation

`envSDM` is not on [CRAN](https://CRAN.R-project.org).

You can install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("dew-landscapes/envSDM")
```
# References
